name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    # only run when pr merged & prevents from running on forks
    if: github.event.pull_request.merged == true && github.repository == 'ssecd/jkn'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # skip test for now, we can always run it locally
      # - name: Test
      #   run: pnpm test

      - name: Build
        run: pnpm build

      - name: Create release PR
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
